---
title: Directly
---

You can run a SafeFn directly by using the `run()` method. This will execute the SafeFn, returning a `ResultAsync` and is intended to be used on the server.

```ts
const mySafeFn = createSafeFn().handler(() => {
  return ok("Success");
});

const res = mySafeFn.run();
//   ^? ResultAsync<"Success", { code: "UNCAUGHT_ERROR", ... }>
```

The arguments required is the `unparsedInput` of the SafeFn. This is either inferred from the input schema, or passed via `unparsedInput<T>()`.

```ts
const mySafeFn = SafeFn.new()
  .input(z.object({ name: z.string() }))
  .handler((args) => {
    return ok(`Hello, ${args.unparsedInput.name}!`);
  });

const res = mySafeFn.run({ firstName: "World" });
// Error:'firstName' does not exist in type '{ name: string; }' [!code highlight]
```

<Callout type="info">
  If you're intending to call the function from the client, such as via a server
  action or through an API route, it's recommended to use the
  [`createAction()`](/docs/run/action) method.
</Callout>

## Return type

The return type of a SafeFn is a `ResultAsync<Value, Error>`. `Value` and `Error` are built as such:

### Value

The output type of your output schema if you defined one, otherwise inferred from your `handler()` or `safeHandler()` return type.

### Error

A union that can contain the following errors:

#### Input parsing

```ts
type E = {
  code: "INPUT_PARSING";
  cause: z.ZodError<T>;
};
```

With `T` as the input of your input schema (this differs from output when using things like `.transform()`). Only applicable if an input schema is defined.
If you defined a parent, its input type will be merged to create one single input error type.

#### Handler

The possible `Err` returns or yield\* s of your `handler()` or `safeHandler()` function. As an arbitrary example:

```ts
function OnlyAbove() {
  let random = Math.random();
  if (random > 0.5) {
    return err({ code: "UNCAUGHT_ERROR" } as const);
  }
  return ok(random);
}

const fn1 = createSafeFn().handler(() => {
  const res = MaybeFail();
  if (res.isErr()) {
    return res;
  }
  return ok(res * 10);
});

const fn2 = createSafeFn().safeHandler(async function* () {
  const res = yield* OnlyAbove();
  return ok(res * 10);
});
```

both of these SafeFns will have an inferred handler error type of

```ts
type E = {
  code: "UNCAUGHT_ERROR";
};
```

#### Uncaught error handler

The inferred error type from your `catch()` error handler. If you didn't set one, the default will be used:

```ts
type E = {
  code: "UNCAUGHT_ERROR";
  cause: "An uncaught error occurred. You can implement a custom error handler by using `catch()`";
};
```

#### Output parsing

```ts
type E = {
  code: "OUTPUT_PARSING";
  cause: z.ZodError<T>;
};
```

With `T` as the input of your output schema (this differs from output when using things like `.transform()`). Only applicable if an output schema is defined. If you defined a parent, its output type will be merged to create one single output error type.

#### Parent

If you set a parent, its error type will be included in the union. These are built in the same way as the child errors above.

### Example

Given the following arbitrary example:

```ts
function maybeFail() {
  if (Math.random() > 0.5) {
    return err({
      code: "TOO_LOW!",
    } as const);
  }
  return ok("hello");
}

const parent = createSafeFn()
  .input(
    z.object({
      parentIn: z.string(),
    }),
  )
  .output(
    z.object({
      parentOut: z.string(),
    }),
  )
  .safeHandler(async function* (args) {
    const res = yield* maybeFail().safeUnwrap();
    return ok({
      parentOut: `${res} ${args.input.parentIn}`,
    });
  });

const child = createSafeFn()
  .use(parent)
  .input(
    z.object({
      childIn: z.string(),
    }),
  )
  .output(
    z.object({
      childOut: z.string(),
    }),
  )
  .handler(async (args) => {
    return ok({
      childOut: `${args.ctx.parentOut} ${args.input.childIn}`,
    });
  })
  .catch((e) => {
    return err({
      code: "Woops!",
    });
  });
```

The return type of `child.run()` will be:

```ts
type Res = ResultAsync<
  {
    childOut: string;
  },
  // Merged error from parent and child
  | {
      code: "INPUT_PARSING";
      cause: z.ZodError<{
        parentIn: string;
        childIn: string;
      }>;
    }
  // Yielded error in parent
  | {
      code: "TOO_LOW!";
    }
  // Parent did not specify a catch handler, so default is used
  | {
      code: "UNCAUGHT_ERROR";
      cause: "An uncaught error occurred. You can implement a custom error handler by using `catch()`";
    }
  // Specified in child catch handler
  | {
      code: "Woops!";
    }
  // Output parsing error
  | {
      code: "OUTPUT_PARSING";
      cause: z.ZodError<{
        parentOut: string;
        childOut: string;
      }>;
    }
>;
```
